# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from worldline.acquiring.sdk.domain.data_object import DataObject


class OriginalTransactionReferences(DataObject):

    __original_scheme_transaction_id: Optional[str] = None
    __original_scheme_transaction_link_id: Optional[str] = None

    @property
    def original_scheme_transaction_id(self) -> Optional[str]:
        """
        | ID assigned by the scheme to identify a transaction through its whole lifecycle.

        Type: str
        """
        return self.__original_scheme_transaction_id

    @original_scheme_transaction_id.setter
    def original_scheme_transaction_id(self, value: Optional[str]) -> None:
        self.__original_scheme_transaction_id = value

    @property
    def original_scheme_transaction_link_id(self) -> Optional[str]:
        """
        | A unique transaction identifier generated by Mastercard to provide consistent linking of related transaction activity throughout the transaction lifecycle.

        Type: str
        """
        return self.__original_scheme_transaction_link_id

    @original_scheme_transaction_link_id.setter
    def original_scheme_transaction_link_id(self, value: Optional[str]) -> None:
        self.__original_scheme_transaction_link_id = value

    def to_dictionary(self) -> dict:
        dictionary = super(OriginalTransactionReferences, self).to_dictionary()
        if self.original_scheme_transaction_id is not None:
            dictionary['originalSchemeTransactionId'] = self.original_scheme_transaction_id
        if self.original_scheme_transaction_link_id is not None:
            dictionary['originalSchemeTransactionLinkId'] = self.original_scheme_transaction_link_id
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'OriginalTransactionReferences':
        super(OriginalTransactionReferences, self).from_dictionary(dictionary)
        if 'originalSchemeTransactionId' in dictionary:
            self.original_scheme_transaction_id = dictionary['originalSchemeTransactionId']
        if 'originalSchemeTransactionLinkId' in dictionary:
            self.original_scheme_transaction_link_id = dictionary['originalSchemeTransactionLinkId']
        return self
