# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .transaction_references_base import TransactionReferencesBase


class TransactionReferencesDispute(TransactionReferencesBase):

    __acquirer_transaction_reference: Optional[str] = None
    __merchant_operation_id: Optional[str] = None
    __retrieval_reference_number: Optional[str] = None
    __scheme_transaction_id: Optional[str] = None
    __scheme_transaction_link_id: Optional[str] = None
    __terminal_id: Optional[str] = None
    __terminal_transaction_reference: Optional[str] = None

    @property
    def acquirer_transaction_reference(self) -> Optional[str]:
        """
        | The reference provided by the acquirer for the original transaction capture that resulted in the dispute. Only present if the acquirer provided a reference in the original transaction capture response.

        Type: str
        """
        return self.__acquirer_transaction_reference

    @acquirer_transaction_reference.setter
    def acquirer_transaction_reference(self, value: Optional[str]) -> None:
        self.__acquirer_transaction_reference = value

    @property
    def merchant_operation_id(self) -> Optional[str]:
        """
        | The merchant's unique identifier for the original transaction capture request that resulted in the dispute. Only present if the merchant provided an ``operationId`` in the original transaction capture request.

        Type: str
        """
        return self.__merchant_operation_id

    @merchant_operation_id.setter
    def merchant_operation_id(self, value: Optional[str]) -> None:
        self.__merchant_operation_id = value

    @property
    def retrieval_reference_number(self) -> Optional[str]:
        """
        | Retrieval reference number (RRN) for transaction

        Type: str
        """
        return self.__retrieval_reference_number

    @retrieval_reference_number.setter
    def retrieval_reference_number(self, value: Optional[str]) -> None:
        self.__retrieval_reference_number = value

    @property
    def scheme_transaction_id(self) -> Optional[str]:
        """
        | ID assigned by the scheme to identify a transaction through its whole lifecycle.

        Type: str
        """
        return self.__scheme_transaction_id

    @scheme_transaction_id.setter
    def scheme_transaction_id(self, value: Optional[str]) -> None:
        self.__scheme_transaction_id = value

    @property
    def scheme_transaction_link_id(self) -> Optional[str]:
        """
        | A unique transaction identifier generated by Mastercard to provide consistent linking of related transaction activity throughout the transaction lifecycle.

        Type: str
        """
        return self.__scheme_transaction_link_id

    @scheme_transaction_link_id.setter
    def scheme_transaction_link_id(self, value: Optional[str]) -> None:
        self.__scheme_transaction_link_id = value

    @property
    def terminal_id(self) -> Optional[str]:
        """
        | The identifier of the terminal

        Type: str
        """
        return self.__terminal_id

    @terminal_id.setter
    def terminal_id(self, value: Optional[str]) -> None:
        self.__terminal_id = value

    @property
    def terminal_transaction_reference(self) -> Optional[str]:
        """
        | The reference of the transaction from the terminal used in the original transaction capture that resulted in the dispute.

        Type: str
        """
        return self.__terminal_transaction_reference

    @terminal_transaction_reference.setter
    def terminal_transaction_reference(self, value: Optional[str]) -> None:
        self.__terminal_transaction_reference = value

    def to_dictionary(self) -> dict:
        dictionary = super(TransactionReferencesDispute, self).to_dictionary()
        if self.acquirer_transaction_reference is not None:
            dictionary['acquirerTransactionReference'] = self.acquirer_transaction_reference
        if self.merchant_operation_id is not None:
            dictionary['merchantOperationId'] = self.merchant_operation_id
        if self.retrieval_reference_number is not None:
            dictionary['retrievalReferenceNumber'] = self.retrieval_reference_number
        if self.scheme_transaction_id is not None:
            dictionary['schemeTransactionId'] = self.scheme_transaction_id
        if self.scheme_transaction_link_id is not None:
            dictionary['schemeTransactionLinkId'] = self.scheme_transaction_link_id
        if self.terminal_id is not None:
            dictionary['terminalId'] = self.terminal_id
        if self.terminal_transaction_reference is not None:
            dictionary['terminalTransactionReference'] = self.terminal_transaction_reference
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'TransactionReferencesDispute':
        super(TransactionReferencesDispute, self).from_dictionary(dictionary)
        if 'acquirerTransactionReference' in dictionary:
            self.acquirer_transaction_reference = dictionary['acquirerTransactionReference']
        if 'merchantOperationId' in dictionary:
            self.merchant_operation_id = dictionary['merchantOperationId']
        if 'retrievalReferenceNumber' in dictionary:
            self.retrieval_reference_number = dictionary['retrievalReferenceNumber']
        if 'schemeTransactionId' in dictionary:
            self.scheme_transaction_id = dictionary['schemeTransactionId']
        if 'schemeTransactionLinkId' in dictionary:
            self.scheme_transaction_link_id = dictionary['schemeTransactionLinkId']
        if 'terminalId' in dictionary:
            self.terminal_id = dictionary['terminalId']
        if 'terminalTransactionReference' in dictionary:
            self.terminal_transaction_reference = dictionary['terminalTransactionReference']
        return self
